global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
remoteWrite:
   - url: https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/ws-95fc630c-ffde-42e3-a1fa-6ed37a3bec08/api/v1/remote_write    
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'ec2_aws_node_exporter_discovery'
    ec2_sd_configs:
      - port: 9100 # referred to nodeExporter exposed port
        role_arn: arn:aws:iam::624997202235:role/ecsInstanceRole
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - ecs-poc-essential-asg
  - job_name: ecs_CAdvisor
    ec2_sd_configs:
      - port: 9200 # referred to cAdvisor exposed port
        role_arn: arn:aws:iam::624997202235:role/ecsInstanceRole
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - ecs-poc-essential-asg
 
