global:
  scrape_interval: 60s
  external_labels:
    monitor: 'devopsage-monitor'
    
remote_read:
  - url: http://18.138.243.173:7201/api/v1/prom/remote/read

remote_write:
  - url: http://18.138.243.173:7201/api/v1/prom/remote/write
    write_relabel_configs:
      - target_label: metrics_storage
        replacement: m3db_remote
        
#remote_write:
#  -
#    url: https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/ws-95fc630c-ffde-42e3-a1fa-6ed37a3bec08/api/v1/remote_write
#    sigv4:
#        region: ap-southeast-1
#    queue_config:
#        max_samples_per_send: 1000
#        max_shards: 200
#        capacity: 2500
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'ec2_aws_node_exporter_discovery'
    ec2_sd_configs:
      - port: 9100 # referred to nodeExporter exposed port
        role_arn: arn:aws:iam::624997202235:role/ecsInstanceRole
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - EC2ContainerService-Prometheus-poc-EcsInstanceAsg-1MQBS8VWA8JQ5
  - job_name: ecs_CAdvisor
    ec2_sd_configs:
      - port: 9200 # referred to cAdvisor exposed port
        role_arn: arn:aws:iam::624997202235:role/ecsInstanceRole
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - EC2ContainerService-Prometheus-poc-EcsInstanceAsg-1MQBS8VWA8JQ5
  - job_name: app
    file_sd_configs:
      - files:
          - /mnt/efs/data/ecs_file_sd.yml
        refresh_interval: 1m

 
